// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  contact_blurb: dynamic(() => import("./ContactBlurb")),
  contact_form: dynamic(() => import("./ContactForm")),
  content_index: dynamic(() => import("./ContentIndex")),
  experience: dynamic(() => import("./Experience")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  scroll_list: dynamic(() => import("./ScrollList")),
  text_block: dynamic(() => import("./TextBlock")),
};
